name: movie_shaker
description: "Canâ€™t decide what to watch? Just shake your phone and get a random movie suggestion instantly! Fast, fun, and perfect for movie nights."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

workspace:
  - packages/ui_components
  - packages/localization

dependencies:
  flutter:
    sdk: flutter

  # localization
  localization: 1.0.0

  # ui
  cupertino_icons: 1.0.8
  ui_components: 1.0.0

  # state management / di
  hooks_riverpod: 2.6.1
  flutter_hooks: 0.21.2
  riverpod_annotation: 2.6.1

  # navigation
  go_router: 16.0.0

  # logger
  logger: 2.6.0
  pretty_dio_logger: 1.4.0

  # network
  dio: 5.8.0+1
  retrofit: 4.6.0

  # data classes
  freezed: 3.0.0
  freezed_annotation: 3.1.0
  json_serializable: 6.9.5

  # shake gesture
  sensors_plus: 6.1.1

  # stream transformers
  rxdart: 0.28.0

  # dart utils
  collection: 1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # momorepo  tools
  melos: 7.2.0

  # code generation
  build_runner: 2.5.4
  riverpod_generator: 2.6.5
  go_router_builder: 3.0.0
  retrofit_generator: 9.7.0

  # lints
  custom_lint: 0.7.6
  riverpod_lint: 2.6.5
  dart_code_metrics_presets: 2.24.0

  # launcher icons gen
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.4.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/launch_icons/

melos:
  command:
    bootstrap:
      runPubGetInParallel: false
      usePubspecOverrides: true

  scripts:
    analyze:
      exec:
        concurrency: 1
      run: /bin/bash $MELOS_ROOT_PATH/scripts/lint.sh
    code_gen:
      exec:
        concurrency: 1
      packageFilters:
        ignore: "localization"
      run: /bin/bash $MELOS_ROOT_PATH/scripts/run_code_generation.sh